### ISSUE TITLE
Legacy editor says “Saved” after trying to save invalid CNXML

### ISSUE THREAD

**Issue by kerwinso** [Rhaptos/Products.RhaptosModuleEditor#20]
The editor says “Saved” after inputting duplicate IDs. Confusing user experience. Did it really get saved? Is this a regression?

![2a97e06f-7ad9-4fd8-b5b7-cbe0aebdbaae](https://user-images.githubusercontent.com/11298165/39525436-9550a3b2-4de1-11e8-95bb-381c458ec931.png)

**Comment by reedstrm** [comment]
Not-a-bug. Not-a-regression. Both message are correct: the content was saved, and it is not valid. (Just tested on production) It was always a design requirement to save whatever the author threw at us, but only _publish_ valid content.
